os: windows
language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
script:
  - mvn verify
notifications:
  email:
    recipients:
      - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
on_failure: always
