os: windows
language: bash
cache:
  directories:
    - $HOME/.m2
install:
  - choco install jdk8
  - choco install maven
script:
  - C:\Users\travis\.m2\bin\mvn verify
notifications:
  email:
    recipients:
      - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
on_failure: always
