jobs:
  include:
    - os: windows
      language: bash
    - os: linux
      language: java
      jdk: openjdk8
cache:
  directories:
    - $HOME/.m2
install:
  - source ./travisCiSetup.sh
script:
  - mvn verify -DtrimStackTrace=false
notifications:
  email:
    recipients:
      - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
on_failure: always
