os: windows
language: bash
cache:
  directories:
    - $HOME/.m2
install:
  - choco install jdk8
  - choco install maven
  - export JAVA_HOME="/c/Program Files/Java/jdk1.8.0_211"
  - ls /c/ProgramData/chocolatey/lib/maven
  - export PATH=$PATH:/c/ProgramData/chocolatey/lib/maven:$JAVA_HOME/bin
script:
  - mvn verify
notifications:
  email:
    recipients:
      - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
on_failure: always
